version: 0.1
phases:
install:
  commands:
    - yarn install
pre_build:
  commands:
    - yarn lint
    # - command
build:
  commands:
    - yarn build
    # - command
post_build:
  commands:
    - ls -al
    - aws s3 cp --recursive dist/ s3://admin.chosajang.com